// from frontend. 

POST http://localhost:8080/api/create-user
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiIsImtpZCI6IjM3MzAwNzY5YTA3ZTA1MTE2ZjdlNTEzOGZhOTA5MzY4NWVlYmMyNDAiLCJ0eXAiOiJKV1QifQ.eyJpc3MiOiJodHRwczovL3NlY3VyZXRva2VuLmdvb2dsZS5jb20vdm9sbGV5cS00NjUyNCIsImF1ZCI6InZvbGxleXEtNDY1MjQiLCJhdXRoX3RpbWUiOjE3NzUwNzg3NDksInVzZXJfaWQiOiJXSmdQdkN0d1loVEROdloyOEIzejk1YUlsMWkxIiwic3ViIjoiV0pnUHZDdHdZaFRETnZaMjhCM3o5NWFJbDFpMSIsImlhdCI6MTc3NTA3ODc0OSwiZXhwIjoxNzc1MDgyMzQ5LCJlbWFpbCI6InRoZWZhc3QzQGdtYWlsLmNvbSIsImVtYWlsX3ZlcmlmaWVkIjpmYWxzZSwiZmlyZWJhc2UiOnsiaWRlbnRpdGllcyI6eyJlbWFpbCI6WyJ0aGVmYXN0M0BnbWFpbC5jb20iXX0sInNpZ25faW5fcHJvdmlkZXIiOiJwYXNzd29yZCJ9fQ.YSm_dbVEc-NISblGzHcUPAV810f79hTgB6C7bv9aNTIfTTMhcRt_SsStBkbcgdUZzng-_7aqyuwv2IrZ4u4e5XZnNHEUi5sM9BraWbNYSWvJafl82BcSoBkSbcMWFC8jXXn1cugS5_UQnvG7dEFVJY2VCeKWinTY1JZpPGdu-awUlPNzOFMxFuzSouagYhvUaf22NjYU3TXSt4Jqlp2ZGxlbmDo_VKhzcuKZihPxGfOfXgRRs_xxbZKK_l8GV5c4kLYaXZr2Px6lJ70KmxDOuyipp298B8Wr-0BeV2cCsINcStGiRTprNJUtYVaVFceUkmNsi5CIjEZFBLGWS2eCzw

{   
  "name": "JohnDoe",
  "email": "john@example.com",
  "avatarUrl": "https://example.com/avatar.png",
  "createdAt": "2026-03-26T12:00:00Z",
  "role": "user",
  "stats": {
    "gamesPlayed": 10,
    "wins": 7
  }
}

// this makes a user create a team. I have the id of the team as 24 and the members of the team should be a list with the userID.
###

POST http://localhost:8080/api/create-team
Content-Type: application/json

{
  "id": "24",
  "name": "TheGreatestTeam",
  "members": [123567],
  "createdAt": "2026-03-26T12:00:00Z",
  "settings": {
    "color": "FFFF",
    "numberOfPlayers": 8
  }
}

// make a user join a team
###
PUT http://localhost:8080/api/join-team/24
Content-Type: application/json
###
DELETE http://localhost:8080/api/delete-team/24
Content-Type: application/json
{
  "userID":"1234567"
}
// probably need to make a collection called list of teams.
// so it'll post in two different areas. 

###
GET http://localhost:8080/api/verify-token
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiIsImtpZCI6IjM3MzAwNzY5YTA3ZTA1MTE2ZjdlNTEzOGZhOTA5MzY4NWVlYmMyNDAiLCJ0eXAiOiJKV1QifQ.eyJpc3MiOiJodHRwczovL3NlY3VyZXRva2VuLmdvb2dsZS5jb20vdm9sbGV5cS00NjUyNCIsImF1ZCI6InZvbGxleXEtNDY1MjQiLCJhdXRoX3RpbWUiOjE3NzUwNzg3NDksInVzZXJfaWQiOiJXSmdQdkN0d1loVEROdloyOEIzejk1YUlsMWkxIiwic3ViIjoiV0pnUHZDdHdZaFRETnZaMjhCM3o5NWFJbDFpMSIsImlhdCI6MTc3NTA3ODc0OSwiZXhwIjoxNzc1MDgyMzQ5LCJlbWFpbCI6InRoZWZhc3QzQGdtYWlsLmNvbSIsImVtYWlsX3ZlcmlmaWVkIjpmYWxzZSwiZmlyZWJhc2UiOnsiaWRlbnRpdGllcyI6eyJlbWFpbCI6WyJ0aGVmYXN0M0BnbWFpbC5jb20iXX0sInNpZ25faW5fcHJvdmlkZXIiOiJwYXNzd29yZCJ9fQ.YSm_dbVEc-NISblGzHcUPAV810f79hTgB6C7bv9aNTIfTTMhcRt_SsStBkbcgdUZzng-_7aqyuwv2IrZ4u4e5XZnNHEUi5sM9BraWbNYSWvJafl82BcSoBkSbcMWFC8jXXn1cugS5_UQnvG7dEFVJY2VCeKWinTY1JZpPGdu-awUlPNzOFMxFuzSouagYhvUaf22NjYU3TXSt4Jqlp2ZGxlbmDo_VKhzcuKZihPxGfOfXgRRs_xxbZKK_l8GV5c4kLYaXZr2Px6lJ70KmxDOuyipp298B8Wr-0BeV2cCsINcStGiRTprNJUtYVaVFceUkmNsi5CIjEZFBLGWS2eCzw

###

// this is for the user with the name bobby. 
###

GET http://localhost:8080/api/user
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiIsImtpZCI6IjM3MzAwNzY5YTA3ZTA1MTE2ZjdlNTEzOGZhOTA5MzY4NWVlYmMyNDAiLCJ0eXAiOiJKV1QifQ.eyJpc3MiOiJodHRwczovL3NlY3VyZXRva2VuLmdvb2dsZS5jb20vdm9sbGV5cS00NjUyNCIsImF1ZCI6InZvbGxleXEtNDY1MjQiLCJhdXRoX3RpbWUiOjE3NzUwOTk0NzAsInVzZXJfaWQiOiJMZUtsUEs0djd3VUdvMHhDUG51bXJCa3Q5Z1QyIiwic3ViIjoiTGVLbFBLNHY3d1VHbzB4Q1BudW1yQmt0OWdUMiIsImlhdCI6MTc3NTA5OTQ3MCwiZXhwIjoxNzc1MTAzMDcwLCJlbWFpbCI6ImJvYjJAZ21haWwuY29tIiwiZW1haWxfdmVyaWZpZWQiOmZhbHNlLCJmaXJlYmFzZSI6eyJpZGVudGl0aWVzIjp7ImVtYWlsIjpbImJvYjJAZ21haWwuY29tIl19LCJzaWduX2luX3Byb3ZpZGVyIjoicGFzc3dvcmQifX0.YVZuPkyBLzFEzYMB41hW75CJrBIcffKOcKI_HkFZfHVDAhqgQs08WZD4wFXtgQDYUu1TnHDzk5aL6n2AkgHlWikjb8i-rwWdh1Z5_d50LPF_KiSjOdqmXS9UlQqrDFqSdyy6APElAVYMOB8nJM3lgku1BbcdjvPwR8Ydvs9B8Yzl7eeljHBAjdil6lp2V9XvEeeUWvZhCQMfdBxxkxiQOpt_NOqtss0ZsZyGzXBT86QsCWszGfQ-DHcY3_jAFzG5iKZGzK5wqlpIBZIfjUaxVP_AYstIJYXpUTRfch6ME645G07xg5yqXU3RTS508PeQBDw-w8dPUlnwSKs5Ol3WRw
